Import('env')

env.Append(CPPPATH=[Dir('.')])


env.add_sources([
'fnet_arp.c',
'fnet_checksum.c',
'fnet_error.c',
'fnet_eth.c',
'fnet_icmp.c',
'fnet_icmp6.c',
'fnet_igmp.c',
'fnet_inet.c',
'fnet_ip.c',
'fnet_ip6.c',
'fnet_isr.c',
'fnet_loop.c',
'fnet_mempool.c',
'fnet_mld.c',
'fnet_nd6.c',
'fnet_netbuf.c',
'fnet_netif.c',
'fnet_prot.c',
'fnet_raw.c',
'fnet_socket.c',
'fnet_stack.c',
'fnet_stdlib.c',
'fnet_tcp.c',
'fnet_timer.c',
'fnet_udp.c'
])

