import glob
import os

Import('env')

mixim_path=env.cometos_externals_path+'/MiXiM'

# Search for sources
env.add_sources(env.get_sources(mixim_path, ignore_paths=["{0}/base/messages".format(mixim_path), "{0}/modules/messages".format(mixim_path)]))

#SConscript("base/messages/SConscript")
#SConscript("modules/messages/SConscript")

# Include all directories
env.Append(CPPPATH=[Dir(x[0]) for x in os.walk(env.cometos_externals_path+'/MiXiM')])
