Import('env')

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'fnet_mk.c',
'fnet_mk_cache.c',
'fnet_mk_eth.c',
'fnet_mk_flash.c',
'fnet_mk_isr.c',
'fnet_mk_isr_inst.c',
'fnet_mk_serial.c',
'fnet_mk_stdlib.c',
'fnet_mk_timer.c',
'fnet_mk_low.S'
])

